### ISSUE TITLE
думи за търсачката

### ISSUE THREAD

**Issue by 3dprintingcnccutting** [3dprintingcnccutting/3dprintingcnccutting.github.io#5]
Разпитах няколко човека, какво биха написали, ако търсят нещо за 3д принтиране. Повечето казаха, че биха търсили на местно ниво - градът в който живеят, ето така:
3d printing sofia
3d printing plovdiv
3d printing varna
3d printing veliko tyrnovo
3d printing ruse
3d printing razgrad
3d printing burgas
3d printing dobich
3d printing bulgaria  и други такива в комбинация с български градове
на мен ми хрумна в добавка и следното:
3d printing toys      3д принтинране на играчки
3d printing tools     3д принтиране на инструменти
3d printing custom parts   3д принтиране на детайли по поръчка
3d printing car parts       3д принтиране на части за коли/автомобили
3d printing tool holder   3д принтиране на стойка за инструменти
3d printing keys holder   3д принтиране на стойка/закачалка за ключове
3d printing business card    3д принтиране на визитки
3d printing business card holder    3д принтиране на стойки за визитни картички
3d printing boxes    3д принтира не на кутийки
3d printing shelf support   3д принтиране на подпора/стойка за рафт

Тези "тагове" може ли да ги добавим и на английски и на български или да си избера само единия език?

**Comment by NewestUser** [comment]
Трябва да разучим допълнително, как се оптимизира за SEO (search engine optimization)
Попринцип няма ограничение за слагане на ключови думи в един сайт. Обаче какъв е оптималния брой и има ли значение подредбата им е друг въпрос, на който аз в момента не мога да отговоря.

**Comment by NewestUser** [comment]
Добавям един guide за SEO и best practices.
Когато имам време ще го прегледам:
https://support.google.com/webmasters/answer/7451184?hl=en
